# Generated by Django 5.1.4 on 2025-01-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_alter_planificacion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion',
            name='nombre_tema',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='nombre_unidad',
        ),
    ]
