# Generated by Django 5.1.4 on 2025-01-04 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
        ('planificacion', '0003_remove_planificacion_nombre_tema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planificacion', to='materia.materia'),
        ),
    ]
