# Generated by Django 5.1.4 on 2025-01-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno_tarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnotarea',
            name='calificacion_binaria',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='alumnotarea',
            name='calificacion_conceptual',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='alumnotarea',
            name='calificacion_numerica',
            field=models.FloatField(null=True),
        ),
    ]
