# Generated by Django 5.1.4 on 2025-01-11 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
        ('alumno_tarea', '0002_alter_alumnotarea_calificacion_binaria_and_more'),
        ('tarea_asignada', '0003_rename_materia_tareaasignada_materia_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnotarea',
            name='alumno_id',
        ),
        migrations.RemoveField(
            model_name='alumnotarea',
            name='tarea_asignada_id',
        ),
        migrations.AddField(
            model_name='alumnotarea',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno_tareas', to='alumno.alumno'),
        ),
        migrations.AddField(
            model_name='alumnotarea',
            name='tarea_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno_tareas', to='tarea_asignada.tareaasignada'),
        ),
    ]
