# Generated by Django 5.1.4 on 2025-01-12 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno_tarea', '0009_alter_alumnotarea_tarea_asignada_id'),
        ('tarea_asignada', '0004_tareaasignada_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnotarea',
            name='tarea_asignada_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno_tareas', to='tarea_asignada.tareaasignada'),
        ),
    ]
