# Generated by Django 5.1.4 on 2025-01-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subtema', '0003_subtema_fecha_fin_subtema_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtemaAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('subtema_id', models.ForeignKey(db_column='subtema_id', on_delete=django.db.models.deletion.CASCADE, related_name='subtemas_anuales', to='subtema.subtema')),
            ],
        ),
    ]
