# Generated by Django 5.1.4 on 2025-01-14 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planificacion', '0004_alter_planificacion_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_clase', models.CharField(max_length=50)),
                ('detalle', models.TextField()),
                ('planificacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.planificacion')),
            ],
        ),
    ]
