# Generated by Django 5.1.4 on 2025-01-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_alter_planificacion_materia'),
        ('planificacion_diaria', '0002_alter_planificaciondiaria_planificacion_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planificaciondiaria',
            constraint=models.UniqueConstraint(fields=('planificacion_id', 'fecha'), name='unique_planificacion_fecha'),
        ),
    ]
