# Generated by Django 5.1.4 on 2025-01-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno_asistencia', '0002_rename_curso_id_alumnoasistencia_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnoasistencia',
            old_name='curso',
            new_name='curso_id',
        ),
    ]
