# Generated by Django 5.1.4 on 2025-01-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno_asistencia', '0003_rename_curso_alumnoasistencia_curso_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoasistencia',
            name='falta_justificada',
            field=models.BooleanField(default=False),
        ),
    ]
