# Generated by Django 5.1.4 on 2025-01-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno_asistencia', '0004_alumnoasistencia_falta_justificada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnoasistencia',
            name='valoracion',
        ),
    ]
