# Generated by Django 5.1.4 on 2025-01-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema_notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotaNumerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_minima', models.IntegerField()),
                ('nota_maxima', models.IntegerField()),
                ('rango_minimo', models.IntegerField()),
                ('sistema_notas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_nota_numerico', to='sistema_notas.sistemanotas')),
            ],
        ),
    ]
