# Generated by Django 5.1.4 on 2025-01-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_nota_numerico', '0002_remove_tiponotanumerico_sistema_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponotanumerico',
            name='es_un_examen',
            field=models.BooleanField(default=False),
        ),
    ]
