# Generated by Django 5.1.4 on 2024-12-14 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0004_institucion_unique_institucion_per_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.institucion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institucion', 'nombre'), name='unique_curso_per_institucion')],
            },
        ),
    ]
