# Generated by Django 5.1.4 on 2024-12-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
