# Generated by Django 5.1.4 on 2024-12-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_alter_institucion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
