# Generated by Django 5.1.4 on 2024-12-14 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_alter_institucion_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='institucion',
            constraint=models.UniqueConstraint(fields=('docente', 'nombre'), name='unique_institucion_per_docente'),
        ),
    ]
