# Generated by Django 5.1.4 on 2025-01-09 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema_notas', '0008_rename_tipo_nota_sistemanotas_tipo_nota_tarea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=False)),
                ('martes', models.BooleanField(default=False)),
                ('miercoles', models.BooleanField(default=False)),
                ('jueves', models.BooleanField(default=False)),
                ('viernes', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('sistema_notas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='sistema_notas.sistemanotas')),
            ],
        ),
    ]
