# Generated by Django 5.1.4 on 2025-01-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno_actitudinal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnoactitudinal',
            name='valoracion',
        ),
    ]
