# Generated by Django 5.1.4 on 2025-01-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_nota_conceptual', '0002_tiponotaconceptual_sistema_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponotaconceptual',
            name='tipo',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
