# Generated by Django 5.1.4 on 2025-01-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_nota_conceptual', '0007_alter_tiponotaconceptual_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiponotaconceptual',
            old_name='tipo',
            new_name='tipo_dato',
        ),
    ]
