# Generated by Django 5.1.4 on 2025-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_nota_conceptual', '0009_remove_tiponotaconceptual_tipo_dato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiponotaconceptual',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
