# Generated by Django 5.1.4 on 2025-01-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno_examen', '0002_alter_alumnoexamen_examen_asignado_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnoexamen',
            old_name='calificacion',
            new_name='calificacion_numerica',
        ),
        migrations.AddField(
            model_name='alumnoexamen',
            name='calificacion_binaria',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='alumnoexamen',
            name='calificacion_conceptual',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumnoexamen',
            name='tipo_calificacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
