# Generated by Django 5.1.4 on 2025-01-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0002_remove_tema_fecha_fin_remove_tema_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='fecha_fin',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='fecha_inicio',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
