# Generated by Django 5.1.4 on 2025-01-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0003_tema_fecha_fin_tema_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='unidad',
            field=models.IntegerField(default=1),
        ),
    ]
