# Generated by Django 5.1.4 on 2025-01-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_alter_planificacion_materia'),
        ('tema', '0005_alter_tema_unidad'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tema',
            constraint=models.UniqueConstraint(fields=('id_planificacion', 'unidad'), name='unique_unidad_per_planificacion'),
        ),
    ]
