# Generated by Django 5.1.4 on 2025-01-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tema', '0007_tema_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='user',
        ),
    ]
