# Generated by Django 5.1.4 on 2025-01-11 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tema', '0008_remove_tema_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('es_recuperatorio', models.BooleanField(default=False)),
                ('tema_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes_asignados', to='tema.tema')),
            ],
        ),
    ]
