# Generated by Django 5.1.4 on 2025-01-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_asignado', '0001_initial'),
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenasignado',
            name='periodo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes_asignados', to='periodo.periodo'),
        ),
    ]
