# Generated by Django 5.1.4 on 2025-01-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_asignado', '0003_examenasignado_materia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenasignado',
            name='fecha',
            field=models.DateField(default='2020-01-20'),
            preserve_default=False,
        ),
    ]
