# Generated by Django 5.1.4 on 2024-12-15 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='curso.curso')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('curso', 'nombre'), name='unique_materia_per_curso')],
            },
        ),
    ]
