# Generated by Django 5.1.4 on 2025-01-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0003_alter_curso_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_examenes', models.IntegerField()),
                ('porcentaje_tareas', models.IntegerField()),
                ('porcentaje_actitudinal', models.IntegerField()),
                ('tipo_nota', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistema_notas', to='curso.curso')),
            ],
        ),
    ]
