# Generated by Django 5.1.4 on 2025-01-08 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0002_initial'),
        ('tipo_nota_binario', '0001_initial'),
        ('tipo_nota_numerico', '0002_remove_tiponotanumerico_sistema_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemanotas',
            name='tipo_nota_numerico_id',
        ),
        migrations.AddField(
            model_name='sistemanotas',
            name='tipo_nota_binario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sistema_notas_binario', to='tipo_nota_binario.tiponotabinario'),
        ),
        migrations.AddField(
            model_name='sistemanotas',
            name='tipo_nota_numerico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sistema_notas_numerico', to='tipo_nota_numerico.tiponotanumerico'),
        ),
    ]
