# Generated by Django 5.1.4 on 2025-01-08 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0003_remove_sistemanotas_tipo_nota_numerico_id_and_more'),
        ('tipo_nota_conceptual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemanotas',
            name='tipo_nota_conceptual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sistema_notas_conceptual', to='tipo_nota_conceptual.tiponotaconceptual'),
        ),
    ]
