# Generated by Django 5.1.4 on 2025-01-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0004_sistemanotas_tipo_nota_conceptual'),
        ('tipo_nota_conceptual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemanotas',
            name='tipo_nota_conceptual',
        ),
        migrations.AddField(
            model_name='sistemanotas',
            name='tipo_nota_conceptual',
            field=models.ManyToManyField(blank=True, null=True, related_name='sistema_notas_conceptual', to='tipo_nota_conceptual.tiponotaconceptual'),
        ),
    ]
