# Generated by Django 5.1.4 on 2025-01-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0005_remove_sistemanotas_tipo_nota_conceptual_and_more'),
        ('tipo_nota_conceptual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemanotas',
            name='tipo_nota_conceptual',
            field=models.ManyToManyField(related_name='sistema_notas_conceptual', to='tipo_nota_conceptual.tiponotaconceptual'),
        ),
    ]
