# Generated by Django 5.1.4 on 2025-01-09 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_remove_asistencia_sistema_notas'),
        ('sistema_notas', '0008_rename_tipo_nota_sistemanotas_tipo_nota_tarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemanotas',
            name='asistencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='asistencia.asistencia'),
        ),
    ]
