# Generated by Django 5.1.4 on 2025-01-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0010_sistemanotas_falta_justificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemanotas',
            name='falta_justificada',
            field=models.BooleanField(default=False),
        ),
    ]
