# Generated by Django 5.1.4 on 2025-01-14 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_alter_curso_duracion'),
        ('sistema_notas', '0011_alter_sistemanotas_falta_justificada'),
        ('tipo_nota_binario', '0001_initial'),
        ('tipo_nota_numerico', '0003_tiponotanumerico_es_un_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemanotas',
            name='examen_tipo_nota_binario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sistema_notas_examen_binario', to='tipo_nota_binario.tiponotabinario'),
        ),
        migrations.AddField(
            model_name='sistemanotas',
            name='examen_tipo_nota_numerico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sistema_notas_examen_numerico', to='tipo_nota_numerico.tiponotanumerico'),
        ),
        migrations.AlterField(
            model_name='sistemanotas',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sistema_notas', to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='sistemanotas',
            name='tipo_nota_examen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
