# Generated by Django 5.1.4 on 2025-01-03 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('id_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='tema.tema')),
            ],
        ),
    ]
