# Generated by Django 5.1.4 on 2025-01-09 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planificacion', '0004_alter_planificacion_materia'),
        ('subtema', '0003_subtema_fecha_fin_subtema_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('planificacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.planificacion')),
                ('subtema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtema.subtema')),
            ],
        ),
    ]
