# Generated by Django 5.1.4 on 2025-01-09 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_alter_planificacion_materia'),
        ('planificacion_mensual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionmensual',
            name='planificacion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificacion_mensual', to='planificacion.planificacion'),
        ),
    ]
