# Generated by Django 5.1.4 on 2025-01-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion_mensual', '0003_planificacionmensual_tipo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionmensual',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
