# Generated by Django 5.1.4 on 2025-01-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodo', '0001_initial'),
        ('subtema', '0003_subtema_fecha_fin_subtema_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('periodo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodo.periodo')),
                ('subtema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtema.subtema')),
            ],
        ),
    ]
