# Generated by Django 5.1.4 on 2025-01-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0003_remove_materia_tareas_asignadas'),
        ('tarea_asignada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaasignada',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='materia.materia'),
        ),
    ]
